language: ruby

services:
  - docker

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - |
   if [ "$TRAVIS_BRANCH" == "master" ]; then
     export TAG="latest"
   else
     export TAG="$TRAVIS_BRANCH"
   fi
  - docker build -t saidsef/scapy-containerised:$TAG .
  - docker push saidsef/scapy-containerised
