language: bash

services:
  - docker

git:
  depth: 50
  submodules: true

before_script:
  - docker version
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - docker build -t saidsef/scapy-containerised:$TRAVIS_BRANCH .

after_script:
  - |
   if [ "$TRAVIS_BRANCH" == "master" ]; then
     docker tag push saidsef/scapy-containerised:$TRAVIS_BRANCH push saidsef/scapy-containerised:latest
   fi
  - docker push saidsef/scapy-containerised

notifications:
  email: true