---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scapy
  labels:
    name: classifier
    app: scapy
  annotations:
    app.kubernetes.io/name: scappy
    app.kubernetes.io/instance: scappy
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: scapy
  template:
    metadata:
      labels:
        app: scapy
    spec:
      # hostNetwork: true
      containers:
      - name: scapy
        image: docker.io/saidsef/scapy-containerised:latest
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8080"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - SYS_TIME
        ports:
        - containerPort: 8080
          protocol: TCP
          name: tcp-term
        volumeMounts:
          - name: tempfile
            mountPath: /var/tmp
            subPath: vartemp
        resources:
          requests:
           memory: "1Gi"
           cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
              - pgrep
              - ttyd
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: tcp-term
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
        - name: tempfile
          emptyDir: {}
