---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scapy
  labels:
    app.kubernetes.io/name: scappy
  annotations:
    app.kubernetes.io/name: scappy
    app.kubernetes.io/instance: scappy
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scappy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scappy
    spec:
      # hostNetwork: true
      automountServiceAccountToken: false
      initContainers:
        - name: init
          image: docker.io/busybox:latest
          imagePullPolicy: IfNotPresent
          workingDir: /data
          command:
           - /bin/sh
          args:
           - -c
           - |
             wget https://github.com/P3TERX/GeoLite.mmdb
          volumeMounts:
            - name: tempfile
              mountPath: /data
              subPath: data
              readOnly: false
          securityContext:
            allowPrivilegeEscalation: true
            privileged: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      containers:
      - name: scapy
        image: docker.io/saidsef/scapy-containerised:v2024.12
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8080"
          - name: SCAPY_HISTFILE
            value: "/tmp/.scapy_history"
          - name: SCAPY_USE_LIBPCAP
            value: "yes"
          - name: MPLCONFIGDIR
            value: "/tmp/matplotlib"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
        ports:
        - containerPort: 8080
          protocol: TCP
          name: tcp-term
        volumeMounts:
          - name: tempfile
            mountPath: /data
            subPath: data
            readOnly: false
          - name: tempfile
            mountPath: /app
            subPath: app
          - name: tempfile
            mountPath: /tmp
            subPath: tmp
            readOnly: false
          - name: tempfile
            mountPath: /var/tmp
            subPath: vartmp
            readOnly: false
        resources:
          requests:
           memory: "1Gi"
           cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
              - pgrep
              - ttyd
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: tcp-term
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
        - name: tempfile
          emptyDir:
            sizeLimit: 2Gi
