---
apiVersion: v1
kind: Service
metadata:
  name: scapy
  labels:
    app.kubernetes.io/name: scappy
  annotations:
    app.kubernetes.io/name: scappy
    app.kubernetes.io/instance: scappy
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: scappy
  ports:
    - name: tcp-term
      protocol: TCP
      port: 8080
