---
replicaCount: 1

image:
  repository: docker.io/saidsef/scapy-containerised
  port: &port 8080
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "scapy"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_ADMIN
      - SYS_TIME

service:
  type: ClusterIP
  port: *port

resources:
  requests:
    memory: "1Gi"
    cpu: "100m"
  limits:
    memory: "2Gi"
    cpu: "200m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
