replicaCount: 1

image:
  repository: saidsef/scapy-containerised
  port: 8080
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_ADMIN
      - SYS_TIME

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "100m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
