name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Tag Name
      run: |
        echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: Build docker image
      run: |
        docker build -t saidsef/scapy-containerised:${{ env.TAG }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/saidsef/scapy-containerised:${{ env.TAG }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: |
        docker push saidsef/scapy-containerised:${{ env.TAG }}
  tagging:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'master') }}
    needs: [build]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Tag Value
        run: |
          echo "DATE=v$(echo `date +'%Y.%m'`)" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.DATE }}",
              sha: context.sha
            })
  test:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.ref, 'master') }}
    needs: [build]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run test
        run: |
          kubectl cluster-info
          NS=`cat deployment/kustomization.yml  | grep namespace | awk '{ print $2 }'`
          kubectl create namespace $NS
          kubectl apply -k deployment/
          kubectl get all -n $NS
